.PHONY: clean All

All:
	@echo "----------Building project:[ gpaCalculator - Debug ]----------"
	@cd "gpaCalculator" && "$(MAKE)" -f  "gpaCalculator.mk"
clean:
	@echo "----------Cleaning project:[ gpaCalculator - Debug ]----------"
	@cd "gpaCalculator" && "$(MAKE)" -f  "gpaCalculator.mk" clean
